version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - echo "Installing dependencies"
      - npm install
      
  build:
    commands:
      - echo "Building the application"
      - npm run build  # You might need to adjust this command based on your project's setup

artifacts:
  files: '**/*'
